export const ROUTES = {
  ROOT: '/',
  HOME: '/home',
  MAP: '/map',
  MY_TREES: '/my-trees',
  MY_TREE_ALIAS: '/my-tree',
  PROFILE: '/profile',
  PROFILE_INFO: '/profile/info',
  PROFILE_EDIT: '/profile/edit',
  ADMIN: '/admin',
  ADMIN_VOLUNTEER_INVITE: '/admin/volunteer-invite',
  ADMIN_TREE_EDIT_REQUESTS: '/admin/tree-edit-requests',
  ADMIN_TREE_EDIT_REQUEST_TEAM: '/admin/tree-edit-requests/:teamId',
  ADMIN_TREE_EDIT_REQUEST_DETAIL: '/admin/tree-edit-requests/:teamId/:requestId',
  TREE_NEW: '/trees/new',
  TREE_EDIT: '/trees/:treeId/edit',
  TREE_ADD_REQUEST: '/tree-add-request',
  TREE_EDIT_REQUEST: '/tree-edit-request',
  ROOMS: '/rooms',
  ROOM_LIST: '/room-list',
  TEAMS: '/teams',
  TEEM_LIST: '/teem-list',
  ROOM_TREES: '/rooms/:roomId/trees',
  TREE_LIST: '/tree-list',
  TREE_NAME_SEARCH: '/tree-name-search',
  VOLUNTEER: '/volunteer',
};
